spring:
  datasource :
    url : jdbc:mysql://dockersql:3306/hotel
    username : root
    password : root
  jpa :
    generate-ddl : true
    hibernate :
      ddl-auto: create
    properties :
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql : true
    show-sql : true

server :
  port : 2018