spring:
  datasource :
    url : jdbc:mysql://localhost:3306/Hotel
    username : root
    password : admin
  jpa :
    generate-ddl : true
    hibernate :
      ddl-auto: create
    properties :
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql : true
    show-sql : true